SELECT * 
FROM CovidVaccinations$

SELECT * FROM [Covid info]..CovidDeaths$ ORDER BY 3,4
--SELECT * FROM [Covid info]..CovidVaccinations$ ORDER BY 3,4

--SELECT DATA TO BE USED
SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
FROM [Covid info]..CovidDeaths$ 
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2

--TOTAL CASES VS. TOTAL DEATHS BY PERCENTAGE
--POSSIBILITY OF DYING IF YOU CONTRACT COVID IN NIGERIA 

select location, date, total_cases, total_deaths,(total_deaths/total_cases)*100 as Death_percentage
from [Covid info]..CovidDeaths$
where location like '%nigeria'
order by total_deaths desc

--TOTAL CASESVS. POPULATION
-- SHOWS THE PERCENTAGE OF THE POPULATION THAT HAS CONTRACTED COVID
select location, date, total_cases,population, (total_cases/population)*100 as Infected_percentage
from [Covid info]..CovidDeaths$
--where location like '%nigeria'
WHERE continent IS NOT NULL
order by 1,2

--COUNTRY WITH HIGHEST INFECTION RATE COMPARE TO POPULATION
select location, POPULATION, MAX (TOTAL_CASES) AS HIGHEST_INFECTIONCOUNT, MAX((total_cases/population))*100 AS INFECTED_PERCENTAGE
from [Covid info]..CovidDeaths$
--where location like '%nigeria'
WHERE continent is not null
GROUP BY LOCATION, POPULATION
order BY INFECTED_PERCENTAGE DESC

--COUNTRY WITH THE HIGHEST DEATH
select location, MAX (cast(total_deaths as int))as HIGHES_DEATHRATE
from [Covid info]..CovidDeaths$
--where location like '%nigeria'
where continent is not null
GROUP BY LOCATION
order by HIGHES_DEATHRATE DESC

--COVID INFORMATION BY CONTINENT
select location, MAX (cast(total_deaths as int))as HIGHES_DEATHRATE
from [Covid info]..CovidDeaths$
--where location like '%nigeria'
where continent is  null
GROUP BY location
order by HIGHES_DEATHRATE DESC

--GLOBAL COVID INFORMATION
--TOTAL SUM OF GLOBAL DEATH RATE BY DATE
SELECT DATE, SUM(NEW_CASES) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATH, SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS
DEATHPARCENTAGE
FROM [Covid info]..CovidDeaths$
--where location like '%nigeria'
where continent is NOT NULL
GROUP BY DATE
order by DATE ASC

--TOTAL GLOBAL CASE
--GLOBAL COVID INFORMATION (TOTAL CASES AND TOTAL DEATH RATE)
SELECT  SUM(NEW_CASES) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATH, SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS
DEATHPARCENTAGE
FROM [Covid info]..CovidDeaths$
--where location like '%nigeria'
where continent is NOT NULL



SELECT *
FROM [Covid info]..CovidDeaths$ DEA
JOIN [Covid info]..CovidVaccinations$ VAC

ON DEA.DATE = VAC. DATE
AND DEA.LOCATION = VAC.LOCATION

--TOTAL GLOBAL POPULATION VS VACCINATED

SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.new_vaccinations,
SUM(CAST(VAC.NEW_VACCINATIONS AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)
AS TOTAL_VACCINATIONROLLOVER
FROM [Covid info]..CovidDeaths$ DEA
JOIN [Covid info]..CovidVaccinations$ VAC
ON DEA.DATE = VAC. DATE
AND DEA.LOCATION = VAC.LOCATION
WHERE DEA.continent IS NOT NULL

--TOTAL PERCENTAGE VACCINATED BY COUNTRY
-- USE CTE
WITH POPULATION_VACINATED
AS
(
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.new_vaccinations,
SUM(CAST(VAC.NEW_VACCINATIONS AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)
AS TOTAL_VACCINATIONROLLOVER
FROM [Covid info]..CovidDeaths$ DEA
JOIN [Covid info]..CovidVaccinations$ VAC
ON DEA.DATE = VAC. DATE
AND DEA.LOCATION = VAC.LOCATION
WHERE DEA.continent IS NOT NULL
)
SELECT * , (TOTAL_VACCINATIONROLLOVER/POPULATION)*100 AS PERCENTAGEPOPULATION_VACCINATED
FROM POPULATION_VACINATED

--TEMP TABLE
DROP TABLE IF EXISTS #POPULATION_VACCINATED_BY_PERCENTAGE
CREATE TABLE #POPULATION_VACCINATED_BY_PERCENTAGE
(CONTINENT NVARCHAR (255),
LOCATION NVARCHAR (255),
DATE DATETIME,
POPULATION NUMERIC,
NEW_VACCINATIONS NUMERIC,
TOTAL_VACCINATIONROLLOVER NUMERIC
)

INSERT INTO #POPULATION_VACCINATED_BY_PERCENTAGE
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.new_vaccinations,
SUM(CAST(VAC.NEW_VACCINATIONS AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)
AS TOTAL_VACCINATIONROLLOVER
FROM [Covid info]..CovidDeaths$ DEA
JOIN [Covid info]..CovidVaccinations$ VAC
ON DEA.DATE = VAC. DATE
AND DEA.LOCATION = VAC.LOCATION
WHERE DEA.continent IS NOT NULL

SELECT * , (TOTAL_VACCINATIONROLLOVER/POPULATION)*100 AS PERCENTAGEPOPULATION_VACCINATED
FROM #POPULATION_VACCINATED_BY_PERCENTAGE

ORDER BY 1,2,3

--CREATE VIEWS FOR VISUALIZATION
CREATE VIEW POPULATION_VACCINATED_BY_PERCENTILE AS
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.new_vaccinations,
SUM(CAST(VAC.NEW_VACCINATIONS AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)
AS TOTAL_VACCINATIONROLLOVER
FROM [Covid info]..CovidDeaths$ DEA
JOIN [Covid info]..CovidVaccinations$ VAC
ON DEA.DATE = VAC. DATE
AND DEA.LOCATION = VAC.LOCATION
WHERE DEA.continent IS NOT NULL
--SELECT * , (TOTAL_VACCINATIONROLLOVER/POPULATION)*100 AS PERCENTAGEPOPULATION_VACCINATED
--FROM #POPULATION_VACCINATED_BY_PERCENTAGE

--ORDER BY 1,2,3

SELECT* 
FROM POPULATION_VACCINATED_BY_PERCENTILE











